Issue492 revise mfcc code
QutEcoacoustics/audio-analysis pull request #497
Opened 2021-06-06 23:09 UTC by towsey

# Revision of MFCC code

The purpose of this isse was to check and rework the mfcc code where necessary.
Parts of this code had not been used or revised in a decade.

## Changes
Changes were made in light of my rereading some literature on the calculation of mfcc features. In particular the delta and double-delta features were not being calculated correctly. 
I added three unit tests for the generation of melscale spectrograms and cepstrograms.

## Issues
I am not aware of any remaining issues that need to be addressed re mfcc calculations.

## Visual Changes
The appearance of the mel scale and mfcc spectrograms has not changed noticeably.

## Final Checklist

-   [Anthony ] Assign reviewers if you have permission
-   [ ] Assign labels if you have permission
-   [yes ] Unit tests have been added for changes
-   [ two relevant test classes have been checked] Ensure CI build is passing

2021-06-07 01:38 UTC, atruskie commented
@towsey please confirm all tests pass manually (CI still failing).

Either run all tests from the test explorer, or run `dotnet test` from a prompt in the `audio-analysis` directory

2021-06-07 02:05 UTC, atruskie requested changes
A good PR.

Only changes required are with the unit tests.

- The best solution for tests is encode known values into the test files.
- Another good solution is to encode tolerable range for a result based on a hand calculated example
- The bin files you are using aren't even that useful since you only compare aggregate values anyway - maybe you don't need to commit the spectrums at all?
- If you do need to commit them, maybe a CSV is a better choice? At least the data would not be opaque
  -  The best choice would be arrow or protobuf formats, but we don't support that
  - BinarySerializer is deprecated and will be removed in furture versions of .NET - we can't keep adding new code that depends on it

Also, please ensure you use `OutPutDirectoryTest` as the base class for writing files during tests. In particular the `SaveTestOutput` function will place files in the daily folder we made for you to easily find results:

https://github.com/QutEcoacoustics/audio-analysis/blob/e1a6784f4104aad7aa44d3b736d442295b584a99/tests/Acoustics.Test/TestHelpers/OutputDirectoryTest.cs#L48-L70

2021-06-08 06:07 UTC, towsey commented
I believe I have dealt with these issues now. I hope so because I have just deleted a bunch of binary fixtures!

2021-06-09 01:22 UTC, atruskie approved these changes

2021-06-09 03:00 UTC, merged