Issue469 rescaling of plot graphs
QutEcoacoustics/audio-analysis pull request #499
Opened 2021-06-13 04:45 UTC by towsey

# Title of PR
Rescaling of plots

## Changes
Wrote a unit test to demonstrate that the rescaling of plots is working.

## Issues
None. Except that also change the FFT window to Hanning in MultiRecognizer.cs.
That may or maynot cause a change somewhere.

## Final Checklist

-   [Anthony ] Assign reviewers if you have permission
-   [ ] Assign labels if you have permission
-   [ ] Link issues related to PR
-   [ ] Link any PRs or issues blocking this PR from being merged
-   [ ] Remove/Reduce warnings from edited files
-   [ Yes] Unit tests have been added for changes
-   [ ] Ensure CI build is passing

2021-06-13 05:06 UTC, atruskie commented
Hi @towsey. Good tests but the issue was with the generic recogniser and not the multi recogniser.

You probably just need to add the array scaling call in the generic recogniser class.

But the way, this is what the `imageWidth` argument is used for (your comments frequently indicate you don't know what it is for). It's used to define a fixed width images should be when rendered. Not applicable here but I was reminded by the subject.

2021-06-13 07:06 UTC, towsey commented
I have included a loop to rescale plots to fit the accompanying spectrogram.

2021-06-13 08:22 UTC, atruskie requested changes

2021-06-13 08:22 UTC, atruskie commented on tests/Acoustics.Test/AnalysisPrograms/Recognizers/GenericRecognizerTests.cs
> +            image1.Save(this.TestOutputDirectory + "\\image1.png");
You cannot use backslashes - our tests run on non-windows paltforms.

Use the `this.TestOutputDirectory.CombineFile("WhistleSpectrogram.png")`

2021-06-13 08:22 UTC, atruskie commented on tests/Acoustics.Test/TowseyLibrary/DataToolsTests.cs
> +            concatImage1.Save(this.TestOutputDirectory + "ConcatImage1.png");
Do not join paths with the `+` operator.

Use the `SaveTestOutput` function

This comment applies to all usages in this class.

2021-06-14 07:32 UTC, towsey commented
Very soryy but unfortunately, the work involved in fixing this aparnetly small Plot scaling problem got significantly more difficult because I used the OscillationEvent class in the unit test. It turned out that the functionality for much of Oscillation events was not working. So this latest commit is mostly about fixing oscillation events.

2021-06-15 04:30 UTC, atruskie approved these changes
I've suggested one change. When you're ready let me know and I'll merge this in

2021-06-15 04:30 UTC, atruskie commented on tests/Acoustics.Test/AnalysisPrograms/Recognizers/GenericRecognizerTests.cs
> +                        "LowerBandDTMF_z",
the name of the test method and test profile do not match up.

DTMF tones are harmonic not oscillations. 

Probably not wrong but it is confusing

2021-06-16 03:31 UTC, merged